development:
      host: localhost
      adapter: mysql
      database: machakostti
      port: 3306
      username: root
      password: kipkemoi

test: &test
      host: localhost
      adapter: mysql
      database: mangunow
      port: 3306
      username: root
      password: kipkemoi
production:
      host: localhost
      adapter: mysql
      database: manguthen
      port: 3306
      username: root
      password: kipkemoi
cucumber:
  <<: *test
